title: Azure Document Intelligence OCR
description: This Add-On uses Azure's Document Intelligence API to OCR documents. 
type: object
documents:
  - selected
properties: {}
categories: 
  - extraction
# Acceptable categories are premium, ai, export, bulk, file,  monitor, statistical, and extraction. 
# You can read more about DocumentCloud Add-On categories here: https://www.documentcloud.org/help/add-ons#types-of-add-ons